version: 2

project_name: raccoon

release:
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - make clean

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"

builds:
  - id: darwin-amd64
    main: ./main.go
    binary: raccoon
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: "archives"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - linux
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/raystack/{{.ProjectName}}:latest"
      - "docker.io/raystack/{{.ProjectName}}:{{ .Version }}"
      - "docker.io/raystack/{{.ProjectName}}:{{ .Version }}-amd64"

brews:
  - name: raccoon
    homepage: "https://github.com/raystack/raccoon"
    description: "Event sourcing tool."
    repository:
      owner: raystack
      name: homebrew-tap
    license: "Apache 2.0"
    directory: Formula
    dependencies:
      - name: git
    install: |-
      bin.install "raccoon"
    commit_author:
      name: Ravi Suhag
      email: suhag.ravi@gmail.com
