server:
  websocket:
    conn:
      id_header: "X-User-ID"
      group_header: "X-User-Group"
    port: 8080
    ping_interval_ms: 10000
    pong_wait_interval_ms: 11000
    write_wait_interval: 1000
    pinger_size: 1
    check_origin: true
  grpc:
    port: 8081
  cors:
    enabled: true
    allowed_origin:
      - "http://localhost:3000"
      - "http://localhost:8080"
    allowed_methods:
      - "GET"
      - "HEAD"
      - "POST"
      - "OPTIONS"
    preflight_max_age_seconds: 60

worker:
  distribution_publisher_pattern: "clickstream-%s-log"

publisher:
  type: "kafka"
  kafka:
    client:
      bootstrap_servers: "kafka:9092"
      acks: 1
      retries: 2
      retry_backoff_ms: 100
      statistics_interval_ms: 5000
      queue_buffering_max_messages: 100000
    flush_interval_ms: 1000

metric:
  runtime_stats_record_interval_ms: 1000
  prometheus:
    enabled: true

