env:
  browser: true
  commonjs: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 12
rules:
  quotes: ["error", "single", { "avoidEscape": true }]
  no-console: ["error", allow: ["error"]]
  semi:
    - error
    - always
  import/extensions: [0, {  <js>: "always"  }]
