{
 "title": "Raccoon",
 "time": { "from": "2024-07-27T18:39:56.224Z", "to": "2024-07-27T18:44:57.453Z" },
 "panels": [
  {
   "title": "Delivery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Processing Duration",
     "type": "timeseries",
     "description": "duration from the time request is processed to the time events are published. This metric is calculated per event by following formula(PublishedTime - ProcessedTime)/CountEvents",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(worker_processing_duration_milliseconds_bucket[1m])) by (le, worker))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Server Processing Latency",
     "type": "timeseries",
     "description": "Duration from the time request is received to the time events are published. This metric is calculated per event by following formula(PublishedTime - ReceivedTime)/CountEvents",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(server_processing_latency_milliseconds_bucket[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Event Processing Duration",
     "type": "timeseries",
     "description": "Duration from the time request is sent to the time events are published. This metric is calculated per event by following formula (PublishedTime - SentTime)/CountEvents",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(event_processing_duration_milliseconds_bucket[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Batch idle time",
     "type": "timeseries",
     "description": "Duration from when the request is received to when the request is processed. High value of this metric indicates the publisher is slow.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(batch_idle_in_channel_milliseconds_bucket[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Data Ingested per minute",
     "type": "timeseries",
     "description": "Total byte received in requests",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(events_rx_bytes_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Batches read per minute",
     "type": "timeseries",
     "description": "Request count",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "targets": [
      { "expr": "rate(batches_read_total[1m])", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Events Ingested per minute",
     "type": "timeseries",
     "description": "Number of events received in requests",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "targets": [
      { "expr": "rate(events_rx_total[1m])", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Duplicate Events",
     "type": "timeseries",
     "description": "Number of duplicate events",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "targets": [
      { "expr": "events_duplicate_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Event Round Trip Time",
     "type": "timeseries",
     "description": "Time taken from event being consumed from the queue to being acked by the ack handler.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(event_rtt_ms_bucket[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ack Latency",
     "type": "timeseries",
     "description": "Time difference between ack function called by producer and processing by the ack handler.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(ack_event_rtt_ms_bucket[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap (Allocated)",
     "type": "timeseries",
     "description": "Bytes of allocated heap objects",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "server_mem_heap_alloc_bytes_current",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap (In Use)",
     "type": "timeseries",
     "description": "in-use spans of heap in bytes",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "server_mem_heap_inuse_bytes_current",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Objects in Heap",
     "type": "timeseries",
     "description": "Number of allocated heap objects\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "server_mem_heap_objects_total_current",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stack Size (In Use)",
     "type": "timeseries",
     "description": "Bytes in stack spans\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "server_mem_stack_inuse_bytes_current",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Goroutine Count",
     "type": "timeseries",
     "description": "Number of goroutine spawn in a single flush",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "server_go_routines_count_current",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Connections",
     "type": "timeseries",
     "description": "Number of successful connections established to the server (per minute)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(user_connection_success_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Connections",
     "type": "timeseries",
     "description": "Number of failed connections established to the server (per minute)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(user_connection_failure_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "timeseries",
     "description": "Number of alive connections\n",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "targets": [
      { "expr": "connections_count_current", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "User Session Duration",
     "type": "timeseries",
     "description": "Duration of alive connection per session per connection",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(user_session_duration_milliseconds_bucket[1m])) by (le))",
       "legendFormat": "Average Time"
      }
     ]
    },
    {
     "title": "Connection Close errors",
     "type": "timeseries",
     "description": "Number of connection close errors encountered",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "targets": [
      { "expr": "rate(conn_close_err_count[1m])", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Ping Failure",
     "type": "timeseries",
     "description": "Total ping that server fails to send (per minute)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "rate(server_ping_failure_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pong Failure",
     "type": "timeseries",
     "description": "Total pong that server fails to send (per minute)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "rate(server_pong_failure_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Publisher: Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Produce Time",
     "type": "timeseries",
     "description": "Response time of produce batch method of the kafka producer",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(histogram_quantile(0.50, sum(rate(kafka_producebulk_tt_ms_bucket[1m])) by (le))) ",
       "legendFormat": "Average Time"
      }
     ]
    },
    {
     "title": "Events delivered",
     "type": "timeseries",
     "description": "Number of events delivered to Kafka.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "rate(kafka_messages_delivered_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Undelivered Events",
     "type": "timeseries",
     "description": "Number of events not delivered to Kafka.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "rate(kafka_messages_undelivered_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unknown Topic Errors",
     "type": "timeseries",
     "description": "Number of delivery failures (per-minute) caused by non-existent topics ",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 110 },
     "targets": [
      {
       "expr": "rate(kafka_unknown_topic_failure_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests sent to Brokers",
     "type": "timeseries",
     "description": "Total number of requests sent to Kafka brokers",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 116 },
     "targets": [
      { "expr": "kafka_brokers_tx_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Data transfer to brokers",
     "type": "timeseries",
     "description": "Total number of bytes transmitted to Kafka brokers",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "kafka_brokers_tx_bytes_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Broker round trip time",
     "type": "timeseries",
     "description": "Broker latency / round-trip time in milliseconds",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_brokers_rtt_average_milliseconds",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Publisher: PubSub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delivered Events",
     "type": "timeseries",
     "description": "Number of events delivered to PubSub.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "rate(pubsub_messages_delivered_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Undelivered Events",
     "type": "timeseries",
     "description": "Number of events that were not delivered to PubSub.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "rate(pubsub_messages_undelivered_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unknown Topic Errors",
     "type": "timeseries",
     "description": "Number of delivery failures caused by non-existence of topic in PubSub.\n",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "rate(pubsub_unknown_topic_failure_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Topic Throughput exceeded errors",
     "type": "timeseries",
     "description": "Number of delivery failures caused by exceeding throughput limits on PubSub.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "rate(pubsub_topic_throughput_exceeded_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Topic Limit exceeded errors",
     "type": "timeseries",
     "description": "Number of delivery failures caused by exceeding the limit on number of Topics on PubSub.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "rate(pubsub_topics_limit_exceeded_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Produce Time",
     "type": "timeseries",
     "description": "Response time of produce batch method of the pubsub producer",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(histogram_quantile(0.50, sum(rate(pubsub_producebulk_tt_ms_bucket[1m])) by (le))) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Publisher: Kinesis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events Delivered",
     "type": "timeseries",
     "description": "Number of events successfully delivered to Kinesis.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "rate(kinesis_messages_delivered_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Undelivered Events",
     "type": "timeseries",
     "description": "Number of events not delivered to Kinesis.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "rate(kinesis_messages_undelivered_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unknown Stream Errors",
     "type": "timeseries",
     "description": "Number of delivery failures caused by non-existence of stream in Kinesis.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "rate(kinesis_unknown_stream_failure_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stream Throughput exceeded errors",
     "type": "timeseries",
     "description": "Number of delivery failures caused by exceeding shard throughput limits. This error can also occur if the message size of an event exceeds message size limit ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "rate(kinesis_stream_throughput_exceeded_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stream Limit exceeded errors",
     "type": "timeseries",
     "description": "Number of delivery failures caused due to too many streams in CREATING mode. AWS Kinesis limits how many stream creation requests can be submitted in parallel to 5.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "rate(kinesis_streams_limit_exceeded_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Produce Time",
     "type": "timeseries",
     "description": "Response time of produce batch method of the kinesis producer",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(histogram_quantile(0.50, sum(rate(kinesis_producebulk_tt_ms_bucket[1m])) by (le))) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}