// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: .temp/odpf/raccoon/v1beta1/raccoon.proto

package io.odpf.proton.raccoon;

public final class EventProto {
  private EventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_odpf_raccoon_v1beta1_SendEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_odpf_raccoon_v1beta1_SendEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_odpf_raccoon_v1beta1_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_odpf_raccoon_v1beta1_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_odpf_raccoon_v1beta1_SendEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_odpf_raccoon_v1beta1_SendEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_odpf_raccoon_v1beta1_SendEventResponse_DataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_odpf_raccoon_v1beta1_SendEventResponse_DataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(.temp/odpf/raccoon/v1beta1/raccoon.pro" +
      "to\022\024odpf.raccoon.v1beta1\032\037google/protobu" +
      "f/timestamp.proto\"\233\001\n\020SendEventRequest\022\031" +
      "\n\010req_guid\030\001 \001(\tR\007reqGuid\0227\n\tsent_time\030\002" +
      " \001(\0132\032.google.protobuf.TimestampR\010sentTi" +
      "me\0223\n\006events\030\003 \003(\0132\033.odpf.raccoon.v1beta" +
      "1.EventR\006events\"<\n\005Event\022\037\n\013event_bytes\030" +
      "\001 \001(\014R\neventBytes\022\022\n\004type\030\002 \001(\tR\004type\"\256\002" +
      "\n\021SendEventResponse\0224\n\006status\030\001 \001(\0162\034.od" +
      "pf.raccoon.v1beta1.StatusR\006status\022.\n\004cod" +
      "e\030\002 \001(\0162\032.odpf.raccoon.v1beta1.CodeR\004cod" +
      "e\022\033\n\tsent_time\030\003 \001(\003R\010sentTime\022\026\n\006reason" +
      "\030\004 \001(\tR\006reason\022E\n\004data\030\005 \003(\01321.odpf.racc" +
      "oon.v1beta1.SendEventResponse.DataEntryR" +
      "\004data\0327\n\tDataEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005" +
      "value\030\002 \001(\tR\005value:\0028\001*F\n\006Status\022\026\n\022STAT" +
      "US_UNSPECIFIED\020\000\022\022\n\016STATUS_SUCCESS\020\001\022\020\n\014" +
      "STATUS_ERROR\020\002*\240\001\n\004Code\022\024\n\020CODE_UNSPECIF" +
      "IED\020\000\022\013\n\007CODE_OK\020\001\022\024\n\020CODE_BAD_REQUEST\020\002" +
      "\022\027\n\023CODE_INTERNAL_ERROR\020\003\022%\n!CODE_MAX_CO" +
      "NNECTION_LIMIT_REACHED\020\004\022\037\n\033CODE_MAX_USE" +
      "R_LIMIT_REACHED\020\0052l\n\014EventService\022\\\n\tSen" +
      "dEvent\022&.odpf.raccoon.v1beta1.SendEventR" +
      "equest\032\'.odpf.raccoon.v1beta1.SendEventR" +
      "esponseBS\n\026io.odpf.proton.raccoonB\nEvent" +
      "ProtoP\001Z+github.com/odpf/proton/raccoon/" +
      "v1;raccoonv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_odpf_raccoon_v1beta1_SendEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_odpf_raccoon_v1beta1_SendEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_odpf_raccoon_v1beta1_SendEventRequest_descriptor,
        new java.lang.String[] { "ReqGuid", "SentTime", "Events", });
    internal_static_odpf_raccoon_v1beta1_Event_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_odpf_raccoon_v1beta1_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_odpf_raccoon_v1beta1_Event_descriptor,
        new java.lang.String[] { "EventBytes", "Type", });
    internal_static_odpf_raccoon_v1beta1_SendEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_odpf_raccoon_v1beta1_SendEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_odpf_raccoon_v1beta1_SendEventResponse_descriptor,
        new java.lang.String[] { "Status", "Code", "SentTime", "Reason", "Data", });
    internal_static_odpf_raccoon_v1beta1_SendEventResponse_DataEntry_descriptor =
      internal_static_odpf_raccoon_v1beta1_SendEventResponse_descriptor.getNestedTypes().get(0);
    internal_static_odpf_raccoon_v1beta1_SendEventResponse_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_odpf_raccoon_v1beta1_SendEventResponse_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
