// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: .temp/odpf/raccoon/v1beta1/raccoon.proto

package io.odpf.proton.raccoon;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:odpf.raccoon.v1beta1.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * `event_bytes` is where you put bytes serialized event.
   * </pre>
   *
   * <code>bytes event_bytes = 1 [json_name = "eventBytes"];</code>
   * @return The eventBytes.
   */
  com.google.protobuf.ByteString getEventBytes();

  /**
   * <pre>
   * `type` denotes an event type that the producer of this proto message may set.
   * It is currently used by raccoon to distribute events to respective Kafka topics. However the
   * users of this proto can use this type to set strings which can be processed in their
   * ingestion systems to distribute or perform other functions.
   * </pre>
   *
   * <code>string type = 2 [json_name = "type"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * `type` denotes an event type that the producer of this proto message may set.
   * It is currently used by raccoon to distribute events to respective Kafka topics. However the
   * users of this proto can use this type to set strings which can be processed in their
   * ingestion systems to distribute or perform other functions.
   * </pre>
   *
   * <code>string type = 2 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
