// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package sample;

public final class PageEventProto {
  private PageEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PageEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PageEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string event_guid = 1 [json_name = "eventGuid"];</code>
     * @return The eventGuid.
     */
    java.lang.String getEventGuid();
    /**
     * <code>string event_guid = 1 [json_name = "eventGuid"];</code>
     * @return The bytes for eventGuid.
     */
    com.google.protobuf.ByteString
        getEventGuidBytes();

    /**
     * <code>string event_name = 2 [json_name = "eventName"];</code>
     * @return The eventName.
     */
    java.lang.String getEventName();
    /**
     * <code>string event_name = 2 [json_name = "eventName"];</code>
     * @return The bytes for eventName.
     */
    com.google.protobuf.ByteString
        getEventNameBytes();

    /**
     * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
     * @return Whether the sentTime field is set.
     */
    boolean hasSentTime();
    /**
     * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
     * @return The sentTime.
     */
    com.google.protobuf.Timestamp getSentTime();
    /**
     * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
     */
    com.google.protobuf.TimestampOrBuilder getSentTimeOrBuilder();
  }
  /**
   * Protobuf type {@code PageEvent}
   */
  public static final class PageEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PageEvent)
      PageEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PageEvent.newBuilder() to construct.
    private PageEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PageEvent() {
      eventGuid_ = "";
      eventName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PageEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PageEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              eventGuid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              eventName_ = s;
              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (sentTime_ != null) {
                subBuilder = sentTime_.toBuilder();
              }
              sentTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sentTime_);
                sentTime_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sample.PageEventProto.internal_static_PageEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sample.PageEventProto.internal_static_PageEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sample.PageEventProto.PageEvent.class, sample.PageEventProto.PageEvent.Builder.class);
    }

    public static final int EVENT_GUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object eventGuid_;
    /**
     * <code>string event_guid = 1 [json_name = "eventGuid"];</code>
     * @return The eventGuid.
     */
    @java.lang.Override
    public java.lang.String getEventGuid() {
      java.lang.Object ref = eventGuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventGuid_ = s;
        return s;
      }
    }
    /**
     * <code>string event_guid = 1 [json_name = "eventGuid"];</code>
     * @return The bytes for eventGuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventGuidBytes() {
      java.lang.Object ref = eventGuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventGuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object eventName_;
    /**
     * <code>string event_name = 2 [json_name = "eventName"];</code>
     * @return The eventName.
     */
    @java.lang.Override
    public java.lang.String getEventName() {
      java.lang.Object ref = eventName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventName_ = s;
        return s;
      }
    }
    /**
     * <code>string event_name = 2 [json_name = "eventName"];</code>
     * @return The bytes for eventName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventNameBytes() {
      java.lang.Object ref = eventName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENT_TIME_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp sentTime_;
    /**
     * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
     * @return Whether the sentTime field is set.
     */
    @java.lang.Override
    public boolean hasSentTime() {
      return sentTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
     * @return The sentTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getSentTime() {
      return sentTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sentTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getSentTimeOrBuilder() {
      return getSentTime();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventGuid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventGuid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventName_);
      }
      if (sentTime_ != null) {
        output.writeMessage(3, getSentTime());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventGuid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventGuid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventName_);
      }
      if (sentTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSentTime());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sample.PageEventProto.PageEvent)) {
        return super.equals(obj);
      }
      sample.PageEventProto.PageEvent other = (sample.PageEventProto.PageEvent) obj;

      if (!getEventGuid()
          .equals(other.getEventGuid())) return false;
      if (!getEventName()
          .equals(other.getEventName())) return false;
      if (hasSentTime() != other.hasSentTime()) return false;
      if (hasSentTime()) {
        if (!getSentTime()
            .equals(other.getSentTime())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENT_GUID_FIELD_NUMBER;
      hash = (53 * hash) + getEventGuid().hashCode();
      hash = (37 * hash) + EVENT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getEventName().hashCode();
      if (hasSentTime()) {
        hash = (37 * hash) + SENT_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getSentTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sample.PageEventProto.PageEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sample.PageEventProto.PageEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sample.PageEventProto.PageEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sample.PageEventProto.PageEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sample.PageEventProto.PageEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sample.PageEventProto.PageEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sample.PageEventProto.PageEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sample.PageEventProto.PageEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sample.PageEventProto.PageEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sample.PageEventProto.PageEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sample.PageEventProto.PageEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sample.PageEventProto.PageEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sample.PageEventProto.PageEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PageEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PageEvent)
        sample.PageEventProto.PageEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sample.PageEventProto.internal_static_PageEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sample.PageEventProto.internal_static_PageEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sample.PageEventProto.PageEvent.class, sample.PageEventProto.PageEvent.Builder.class);
      }

      // Construct using sample.PageEventProto.PageEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        eventGuid_ = "";

        eventName_ = "";

        if (sentTimeBuilder_ == null) {
          sentTime_ = null;
        } else {
          sentTime_ = null;
          sentTimeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sample.PageEventProto.internal_static_PageEvent_descriptor;
      }

      @java.lang.Override
      public sample.PageEventProto.PageEvent getDefaultInstanceForType() {
        return sample.PageEventProto.PageEvent.getDefaultInstance();
      }

      @java.lang.Override
      public sample.PageEventProto.PageEvent build() {
        sample.PageEventProto.PageEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sample.PageEventProto.PageEvent buildPartial() {
        sample.PageEventProto.PageEvent result = new sample.PageEventProto.PageEvent(this);
        result.eventGuid_ = eventGuid_;
        result.eventName_ = eventName_;
        if (sentTimeBuilder_ == null) {
          result.sentTime_ = sentTime_;
        } else {
          result.sentTime_ = sentTimeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sample.PageEventProto.PageEvent) {
          return mergeFrom((sample.PageEventProto.PageEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sample.PageEventProto.PageEvent other) {
        if (other == sample.PageEventProto.PageEvent.getDefaultInstance()) return this;
        if (!other.getEventGuid().isEmpty()) {
          eventGuid_ = other.eventGuid_;
          onChanged();
        }
        if (!other.getEventName().isEmpty()) {
          eventName_ = other.eventName_;
          onChanged();
        }
        if (other.hasSentTime()) {
          mergeSentTime(other.getSentTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sample.PageEventProto.PageEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sample.PageEventProto.PageEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object eventGuid_ = "";
      /**
       * <code>string event_guid = 1 [json_name = "eventGuid"];</code>
       * @return The eventGuid.
       */
      public java.lang.String getEventGuid() {
        java.lang.Object ref = eventGuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventGuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string event_guid = 1 [json_name = "eventGuid"];</code>
       * @return The bytes for eventGuid.
       */
      public com.google.protobuf.ByteString
          getEventGuidBytes() {
        java.lang.Object ref = eventGuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventGuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event_guid = 1 [json_name = "eventGuid"];</code>
       * @param value The eventGuid to set.
       * @return This builder for chaining.
       */
      public Builder setEventGuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventGuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string event_guid = 1 [json_name = "eventGuid"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEventGuid() {
        
        eventGuid_ = getDefaultInstance().getEventGuid();
        onChanged();
        return this;
      }
      /**
       * <code>string event_guid = 1 [json_name = "eventGuid"];</code>
       * @param value The bytes for eventGuid to set.
       * @return This builder for chaining.
       */
      public Builder setEventGuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventGuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object eventName_ = "";
      /**
       * <code>string event_name = 2 [json_name = "eventName"];</code>
       * @return The eventName.
       */
      public java.lang.String getEventName() {
        java.lang.Object ref = eventName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string event_name = 2 [json_name = "eventName"];</code>
       * @return The bytes for eventName.
       */
      public com.google.protobuf.ByteString
          getEventNameBytes() {
        java.lang.Object ref = eventName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event_name = 2 [json_name = "eventName"];</code>
       * @param value The eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string event_name = 2 [json_name = "eventName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEventName() {
        
        eventName_ = getDefaultInstance().getEventName();
        onChanged();
        return this;
      }
      /**
       * <code>string event_name = 2 [json_name = "eventName"];</code>
       * @param value The bytes for eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp sentTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sentTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
       * @return Whether the sentTime field is set.
       */
      public boolean hasSentTime() {
        return sentTimeBuilder_ != null || sentTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
       * @return The sentTime.
       */
      public com.google.protobuf.Timestamp getSentTime() {
        if (sentTimeBuilder_ == null) {
          return sentTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sentTime_;
        } else {
          return sentTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
       */
      public Builder setSentTime(com.google.protobuf.Timestamp value) {
        if (sentTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sentTime_ = value;
          onChanged();
        } else {
          sentTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
       */
      public Builder setSentTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (sentTimeBuilder_ == null) {
          sentTime_ = builderForValue.build();
          onChanged();
        } else {
          sentTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
       */
      public Builder mergeSentTime(com.google.protobuf.Timestamp value) {
        if (sentTimeBuilder_ == null) {
          if (sentTime_ != null) {
            sentTime_ =
              com.google.protobuf.Timestamp.newBuilder(sentTime_).mergeFrom(value).buildPartial();
          } else {
            sentTime_ = value;
          }
          onChanged();
        } else {
          sentTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
       */
      public Builder clearSentTime() {
        if (sentTimeBuilder_ == null) {
          sentTime_ = null;
          onChanged();
        } else {
          sentTime_ = null;
          sentTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
       */
      public com.google.protobuf.Timestamp.Builder getSentTimeBuilder() {
        
        onChanged();
        return getSentTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
       */
      public com.google.protobuf.TimestampOrBuilder getSentTimeOrBuilder() {
        if (sentTimeBuilder_ != null) {
          return sentTimeBuilder_.getMessageOrBuilder();
        } else {
          return sentTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : sentTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp sent_time = 3 [json_name = "sentTime"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getSentTimeFieldBuilder() {
        if (sentTimeBuilder_ == null) {
          sentTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getSentTime(),
                  getParentForChildren(),
                  isClean());
          sentTime_ = null;
        }
        return sentTimeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PageEvent)
    }

    // @@protoc_insertion_point(class_scope:PageEvent)
    private static final sample.PageEventProto.PageEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sample.PageEventProto.PageEvent();
    }

    public static sample.PageEventProto.PageEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PageEvent>
        PARSER = new com.google.protobuf.AbstractParser<PageEvent>() {
      @java.lang.Override
      public PageEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PageEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PageEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PageEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sample.PageEventProto.PageEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PageEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PageEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sample.proto\032\037google/protobuf/timestam" +
      "p.proto\"\202\001\n\tPageEvent\022\035\n\nevent_guid\030\001 \001(" +
      "\tR\teventGuid\022\035\n\nevent_name\030\002 \001(\tR\teventN" +
      "ame\0227\n\tsent_time\030\003 \001(\0132\032.google.protobuf" +
      ".TimestampR\010sentTimeB\030\n\006sampleB\016PageEven" +
      "tProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_PageEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PageEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PageEvent_descriptor,
        new java.lang.String[] { "EventGuid", "EventName", "SentTime", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
