name: Release Client - JS

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-js-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@raystack"
      - run: npm install
        working-directory: clients/js
      - run: npm publish --access public
        working-directory: clients/js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
