name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get release tag
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Release the project
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_TOKEN }}
        run: |
          BUILD_CMD='git config --global --add safe.directory /build/src && cd /build/src && goreleaser release --clean'
          echo $BUILD_CMD | docker run \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/.docker:/root/.docker \
            -v "$PWD/:/build/src" \
            -e GITHUB_TOKEN="${GITHUB_TOKEN}" \
            -i --entrypoint /bin/bash \
            goreleaser/goreleaser-cross:v1.22.4
