name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release tag
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: setup docker
        uses: docker-practice/actions-setup-docker@master
      - name: build distributables
        run: |
          BUILD_CMD='git config --global --add safe.directory /build/src && cd /build/src && goreleaser build'
          echo $BUILD_CMD | docker run -i --entrypoint /bin/bash -v "$PWD/:/build/src" goreleaser/goreleaser-cross
          sudo chown -R $USER:$USER dist/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ~v2
          args: release 
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_TOKEN }}