name: Test Raccoon JS Client
on:
  push:
    paths:
      - "clients/js/**"
  pull_request:
    paths:
      - "clients/js/**"
jobs:
  test-js-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
        working-directory: clients/js
      - name: Check formatting
        run: npm run format
        working-directory: clients/js
      - name: Test
        run: npm test
        working-directory: clients/js
