name: Test Raccoon JS Client
on:
  push:
    paths:
      - "clients/js/**"
  pull_request:
    paths:
      - "clients/js/**"
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
        working-directory: clients/js
      - name: Check formatting
        run: npm run format
        working-directory: clients/js
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
        working-directory: clients/js
      - name: Check linting
        run: npm run lint
        working-directory: clients/js
  test-js-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
        working-directory: clients/js
      - name: Test
        run: npm test
        working-directory: clients/js
