name: Test Raccoon GO client
on:
  push:
    paths:
      - "clients/go/**"
    branches:
      - main
  pull_request:
    paths:
      - "clients/go/**"
    branches:
      - main
jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: cd clients/go; go test -count 1 -cover ./...